package com.lim1t.csq.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBNamed;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.stereotype.Service;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;


@Setter
@NoArgsConstructor
@DynamoDbBean
@DynamoDBTable(tableName = "csQuestion")
public class CsQuestion {

    @Getter(onMethod_=@DynamoDbPartitionKey)
    private String csQuestionId; // Primary Key

    @Getter
    private String question;

    @Getter
    private String answer;

    @Builder
    public CsQuestion(String cs_question_id, String question, String answer) {
        this.csQuestionId = cs_question_id;
        this.question = question;
        this.answer = answer;
    }
}
